// <auto-generated />
using System;
using Kerial.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kerial.Migrations
{
    [DbContext(typeof(DbKerialContext))]
    partial class DbKerialContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kerial.Models.Depense", b =>
                {
                    b.Property<int>("idDepense")
                        .HasColumnType("int");

                    b.Property<string>("commentaire")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime");

                    b.Property<string>("devise")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<int>("idUtilisateur")
                        .HasColumnType("int");

                    b.Property<float>("montant")
                        .HasColumnType("real");

                    b.Property<string>("nature")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.HasKey("idDepense")
                        .HasName("PK__Depense__BCBC7CF5CD391601");

                    b.ToTable("Depense");
                });

            modelBuilder.Entity("Kerial.Models.Utilisateur", b =>
                {
                    b.Property<int>("idUtilisateur")
                        .HasColumnType("int");

                    b.Property<string>("devise")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("nomDeFamille")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.HasKey("idUtilisateur")
                        .HasName("PK__Utilisat__5366DB194D8C658B");

                    b.ToTable("Utilisateur");
                });
#pragma warning restore 612, 618
        }
    }
}
